### ISSUE TITLE
Cannot build when targeting `/cjs` with Node 14

### ISSUE THREAD

**Issue by isaachinman** [i18next/i18next-http-middleware#3]
When importing `i18next-http-middleware/cjs` in Node 14, the following error occurs:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cjs' is not defined by "exports" in /next-i18next/examples/simple/node_modules/i18next-http-middleware/package.json
    at applyExports (internal/modules/cjs/loader.js:492:9)
    at resolveExports (internal/modules/cjs/loader.js:508:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (eval at _default (/next-i18next/examples/simple/.next/server/static/Is5pI6bYEY6qbsIXDLIqW/pages/_app.js:10253:31), <anonymous>:1:1)
    at _default (/next-i18next/examples/simple/.next/server/static/Is5pI6bYEY6qbsIXDLIqW/pages/_app.js:10253:31)
    at new NextI18Next (/next-i18next/examples/simple/.next/server/static/Is5pI6bYEY6qbsIXDLIqW/pages/_app.js:9923:66) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by adrai** [comment]
Can you create a reproducable repo?

**Comment by adrai** [comment]
I have an idea...

**Comment by adrai** [comment]
Can you try locally if this would work?
![image](https://user-images.githubusercontent.com/1086194/80870596-c02fb300-8ca7-11ea-8f75-d2f98210fa42.png)

**Comment by adrai** [comment]
> Can you create a reproducable repo? Or is this the build of next-i18next?

Ahh it's this: next-i18next/examples/simple

**Comment by adrai** [comment]
ok...
seeems this works... will imediately publish a new version
```json
    "./cjs": {
      "default": "./cjs/index.js"
    }
```

**Comment by adrai** [comment]
i18next-http-middleware@1.0.1

**Comment by adrai** [comment]
i18next-http-backend@1.0.8

**Comment by isaachinman** [comment]
@adrai That's working great, thanks for a quick response.
