### ISSUE TITLE
Use with Koa?

### ISSUE THREAD

**Issue by robross0606** [i18next/i18next-http-middleware#61]
There are many examples in the README for popular frameworks (express, fastify, deno, etc.) but Koa is missing.  Could we get a simple example of how to apply this middleware to Koa?

**Comment by robross0606** [comment]
This plugin claims it is "not bound to a specific http framework anymore" but all the documentation and examples are for specific HTTP frameworks and there appear to be special functions and variables for multiple specific frameworks.  Is there any actual API documentation?

**Comment by robross0606** [comment]
Or perhaps it would be better to focus on the error I'm getting:
```
  TypeError: next is not a function
      at C:\Code\myApp\node_modules\i18next-http-middleware\cjs\index.js:112:14
      at I18n.loadLanguages (C:\Code\myApp\node_modules\i18next\dist\cjs\i18next.js:2181:21)
      at i18nextMiddleware (C:\Code\myApp\node_modules\i18next-http-middleware\cjs\index.js:111:13)
      at dispatch (C:\Code\myApp\node_modules\koa-compose\index.js:42:32)
      at logger (C:\Code\myApp\node_modules\koa-logger\index.js:67:13)
      at dispatch (C:\Code\myApp\node_modules\koa-compose\index.js:42:32)
      at C:\Code\myApp\src\server.js:218:9
      at dispatch (C:\Code\myApp\node_modules\koa-compose\index.js:42:32)
      at dispatch (C:\Code\myApp\node_modules\koa-router\lib\router.js:399:32)
      at dispatch (C:\Code\myApp\node_modules\koa-compose\index.js:42:32)
      at C:\Code\myApp\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (C:\Code\myApp\node_modules\koa\lib\application.js:186:12)
      at Server.handleRequest (C:\Code\myApp\node_modules\koa\lib\application.js:157:21)
      at Server.emit (node:events:514:28)
      at parserOnIncoming (node:_http_server:1107:12)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by robross0606** [comment]
The problem is that Koa middleware has a different function signature than Express.  For the time being, I've been able to wrap it with an adapter, but I'd prefer to be able to use it without that since this library is touted as not bound to frameworks.  Since there's very limited documentation other than specific examples, I'm not sure how to do that.

**Comment by adrai** [comment]
I'm on it...

**Comment by adrai** [comment]
https://github.com/i18next/i18next-http-middleware/blob/master/example/koa/index.js
